
import React, { useState, useMemo, useEffect } from 'react';
import type { ColumnConfig, ParsedFile, RowData } from '../types';
import { TableIcon, BackIcon, CheckIcon, CloseIcon, BroomIcon } from '../components/Icons';
import { evaluateFormula } from '../utils/formulaEvaluator';
import { processData } from '../utils/fileParser';
import DataCleaningModal from '../components/DataCleaningModal';

interface ConfigurePageProps {
  fileName: string;
  parsedFile: ParsedFile;
  selectedSheet: string;
  onSheetSelect: (sheetName: string) => void;
  initialColumnConfig: ColumnConfig[];
  currentData?: RowData[]; // New prop to persist data
  onConfirm: (config: ColumnConfig[], data: RowData[]) => void;
  onReset: () => void;
}

const DraggableHeader: React.FC<{
  config: ColumnConfig;
  index: number;
  onDragStart: (index: number) => void;
  onDrop: (index: number) => void;
  onLabelChange: (id: string, newLabel: string) => void;
  onRemove: (id: string) => void;
}> = ({ config, index, onDragStart, onDrop, onLabelChange, onRemove }) => {
  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
  };

  return (
    <div
      draggable={!config.formula}
      onDragStart={() => onDragStart(index)}
      onDrop={() => onDrop(index)}
      onDragOver={handleDragOver}
      className={`relative p-3 bg-[var(--bg-contrast)] rounded-md flex items-center gap-2 group ${config.formula ? 'cursor-not-allowed' : 'cursor-grab active:cursor-grabbing'}`}
    >
      <input
        type="text"
        value={config.label}
        onChange={(e) => onLabelChange(config.id, e.target.value)}
        className="flex-grow bg-transparent font-semibold focus:ring-1 focus:ring-[var(--ring-color)] focus:outline-none rounded px-2 py-1 pr-10 min-w-0"
        disabled={!!config.formula}
      />
       {config.formula && <span data-tooltip="This is a calculated column. Its values are generated by a formula." className="text-[var(--color-accent)]">ƒx</span>}
      <button
        onClick={() => onRemove(config.id)}
        className="absolute top-2 right-2 z-10 text-[var(--text-tertiary)] hover:text-red-400 bg-transparent p-1 rounded focus:outline-none focus:ring-1 focus:ring-[var(--ring-color)]"
        aria-label={`Remove column ${config.label}`}
      >
        <CloseIcon className="w-4 h-4" />
      </button>
    </div>
  );
};

const ConfigurePage: React.FC<ConfigurePageProps> = ({
  fileName,
  parsedFile,
  selectedSheet,
  onSheetSelect,
  initialColumnConfig,
  currentData,
  onConfirm,
  onReset,
}) => {
  const [config, setConfig] = useState<ColumnConfig[]>(initialColumnConfig);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  
  // "cleanedData" holds the full dataset as RowData objects.
  const [cleanedData, setCleanedData] = useState<RowData[]>([]);
  const [isCleaningModalOpen, setIsCleaningModalOpen] = useState(false);

  useEffect(() => {
    setConfig(initialColumnConfig);
    
    // If we have existing data (from Dashboard), use it. Otherwise, process raw file.
    if (currentData && currentData.length > 0) {
        setCleanedData(currentData);
    } else if (selectedSheet && parsedFile.sheets[selectedSheet]) {
        const rawData = parsedFile.sheets[selectedSheet];
        const initialProcessed = processData(rawData, initialColumnConfig);
        setCleanedData(initialProcessed);
    }
  }, [initialColumnConfig, selectedSheet, parsedFile, currentData]);

  const sheetNames = Object.keys(parsedFile.sheets);

  const handleLabelChange = (id: string, newLabel: string) => {
    const oldLabel = config.find(c => c.id === id)?.label;
    
    setConfig(prev => prev.map(c => c.id === id ? { ...c, label: newLabel } : c));

    // If we rename a column in config, we must also update the keys in our cleanedData objects
    if (oldLabel && oldLabel !== newLabel) {
        setCleanedData(prevData => prevData.map(row => {
            const newRow = { ...row };
            if (newRow.hasOwnProperty(oldLabel)) {
                newRow[newLabel] = newRow[oldLabel];
                delete newRow[oldLabel];
            }
            return newRow;
        }));
    }
  };

  const handleRemoveColumn = (idToRemove: string) => {
    const isDependency = config.some(c => 
      c.formula?.includes(`{${idToRemove}}`)
    );
    if (isDependency) {
      alert('This column is used in a calculation and cannot be removed. Please remove the calculated column first.');
      return;
    }
    
    const labelToRemove = config.find(c => c.id === idToRemove)?.label;
    setConfig(prev => prev.filter(c => c.id !== idToRemove));

    if (labelToRemove) {
        setCleanedData(prevData => prevData.map(row => {
            const newRow = { ...row };
            delete newRow[labelToRemove];
            return newRow;
        }));
    }
  };

  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
  };
  
  const handleDrop = (dropIndex: number) => {
    if (draggedIndex === null) return;

    const newConfig = [...config];
    const draggedItem = newConfig[draggedIndex];
    
    if (config[dropIndex].formula) {
      setDraggedIndex(null);
      return;
    }

    newConfig.splice(draggedIndex, 1);
    const newDropIndex = draggedIndex < dropIndex ? dropIndex - 1 : dropIndex;
    newConfig.splice(newDropIndex, 0, draggedItem);
    setConfig(newConfig);
    setDraggedIndex(null);
  };

  const previewRows = useMemo(() => {
    const rowsToPreview = cleanedData.slice(0, 5);
    const calculatedColumns = config.filter(c => c.formula);

    return rowsToPreview.map(row => {
        const processedRow = { ...row };
        
        calculatedColumns.forEach(col => {
            const formula = col.formula!;
            const colIdRegex = /\{([^}]+)\}/g;
            let match;
            const dependencies = new Set<string>();
            while ((match = colIdRegex.exec(formula)) !== null) {
                dependencies.add(match[1]);
            }
            
            const valueMap: Record<string, number> = {};
            let canCalculate = true;

            dependencies.forEach(depId => {
                const depConfig = config.find(c => c.id === depId);
                if (!depConfig) {
                    canCalculate = false;
                    return;
                }
                const depValue = processedRow[depConfig.label];
                if (typeof depValue === 'number') {
                    valueMap[depId] = depValue;
                } else {
                    canCalculate = false;
                }
            });

            processedRow[col.label] = canCalculate ? evaluateFormula(formula, valueMap) : null;
        });
        
        return processedRow;
    });

  }, [cleanedData, config]);

  const handleConfirm = () => {
    const calculatedColumns = config.filter(c => c.formula);
    
    const finalData = cleanedData.map(row => {
        const processedRow = { ...row };
        
        calculatedColumns.forEach(col => {
            const formula = col.formula!;
            const colIdRegex = /\{([^}]+)\}/g;
            let match;
            const dependencies = new Set<string>();
            while ((match = colIdRegex.exec(formula)) !== null) {
                dependencies.add(match[1]);
            }
            
            const valueMap: Record<string, number> = {};
            let canCalculate = true;

            dependencies.forEach(depId => {
                const depConfig = config.find(c => c.id === depId);
                if (!depConfig) return;
                const depValue = processedRow[depConfig.label];
                if (typeof depValue === 'number') valueMap[depId] = depValue;
                else canCalculate = false;
            });

            processedRow[col.label] = canCalculate ? evaluateFormula(formula, valueMap) : null;
        });
        return processedRow;
    });

    onConfirm(config, finalData);
  };


  if (!selectedSheet && sheetNames.length > 1) {
    return (
      <div className="w-full max-w-3xl p-8 bg-[var(--bg-card)] rounded-2xl shadow-lg">
        <h2 className="text-2xl font-bold mb-2">Select a Worksheet</h2>
        <p className="text-[var(--text-secondary)] mb-6">Your file "{fileName}" contains multiple sheets. Please choose one to continue.</p>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {sheetNames.map(name => (
            <button
              key={name}
              onClick={() => onSheetSelect(name)}
              className="flex items-center gap-2 p-4 bg-[var(--bg-contrast)] hover:bg-[var(--bg-accent)] hover:text-[var(--text-on-accent)] rounded-lg transition-colors"
            >
              <TableIcon /> {name}
            </button>
          ))}
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="w-full max-w-6xl p-8 bg-[var(--bg-card)] rounded-2xl shadow-lg flex flex-col gap-6">
          <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">
              <div>
                  <h2 className="text-2xl font-bold">Configure Your Data</h2>
                  <p className="text-[var(--text-secondary)]">Rename, reorder, or clean columns before visualization.</p>
              </div>
              <button 
                onClick={() => setIsCleaningModalOpen(true)}
                className="flex items-center gap-2 px-4 py-3 bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg transition-colors font-semibold shadow-md"
              >
                  <BroomIcon className="w-5 h-5" /> Clean Data
              </button>
          </div>

          <div className="bg-black/10 p-4 rounded-lg">
              <h3 className="font-semibold text-lg mb-3">Columns</h3>
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3" data-tooltip="Drag and drop columns to reorder them for your dashboard.">
              {config.map((c, i) => (
                  <DraggableHeader
                  key={c.id}
                  config={c}
                  index={i}
                  onDragStart={handleDragStart}
                  onDrop={handleDrop}
                  onLabelChange={handleLabelChange}
                  onRemove={handleRemoveColumn}
                  />
              ))}
              </div>
          </div>

          <div className="bg-black/10 p-4 rounded-lg overflow-x-auto">
              <div className="flex justify-between items-center mb-3">
                  <h3 className="font-semibold text-lg">Data Preview</h3>
                  <span className="text-xs text-[var(--text-tertiary)]">
                      Showing first 5 rows of {cleanedData.length}
                  </span>
              </div>
              <table className="w-full text-left text-sm">
              <thead>
                  <tr>
                  {config.map(c => <th key={c.id} className="p-2 font-semibold border-b border-[var(--border-color-heavy)]">{c.label}</th>)}
                  </tr>
              </thead>
              <tbody>
                  {previewRows.map((row, rowIndex) => (
                    <tr key={rowIndex} className="border-b border-[var(--border-color)]">
                        {config.map(c => {
                            const value = row[c.label];
                            const displayValue = typeof value === 'number' ? value.toLocaleString(undefined, {maximumFractionDigits: 3}) : String(value ?? '');
                            return <td key={c.id} className="p-2 truncate max-w-[150px]">{displayValue}</td>
                        })}
                    </tr>
                  ))}
              </tbody>
              </table>
          </div>

          <div className="flex justify-between items-center mt-4">
              <button onClick={onReset} className="flex items-center gap-2 text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors">
              <BackIcon /> Back
              </button>
              <button onClick={handleConfirm} className="flex items-center gap-2 bg-[var(--bg-accent)] hover:bg-[var(--bg-accent-hover)] text-[var(--text-on-accent)] font-bold py-2 px-6 rounded-lg transition-colors">
              <CheckIcon /> Confirm & Build Dashboard
              </button>
          </div>
      </div>

      <DataCleaningModal 
        isOpen={isCleaningModalOpen} 
        onClose={() => setIsCleaningModalOpen(false)}
        data={cleanedData}
        columnConfig={config}
        onSave={setCleanedData}
      />
    </>
  );
};

export default ConfigurePage;
